# Generated by Django 4.2.4 on 2023-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='produto_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
